

GET https://localhost:7253/api/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMWNjZmNkNS02ZDAyLTQxNDUtYTMwYy00OTY4OTBkZDJmOGMiLCJqdGkiOiI3MjQ5NDk2Yy04YTczLTRhYWEtYTcxYi1mYzUyZTBmNTM1MTIiLCJnaXZlbl9uYW1lIjoiQWJkZWwiLCJmYW1pbHlfbmFtZSI6IlJhb29mIiwiZXhwIjoxNjgyODQzNDQ5LCJpc3MiOiJBbWlDb2ciLCJhdWQiOiJBbWlDb2cifQ.9KF8id5hW_sHWpURX4y48GZthuX0UT_by18sJ8jKiVw
